name: Build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
          - platform: linux/arm64
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v

      - name: Output Env
        run: echo "GOOS: $GOOS GOARCH: $GOARCH"

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false

